Upgrade to WGPU 22
bevyengine/naga_oil pull request #98
Opened 2024-07-19 22:08 UTC by callym

This currently doesn't pass the tests, I think because `naga` removed the `PartialEq` implementation on a bunch of types (https://github.com/gfx-rs/wgpu/pull/5818)

2024-07-20 04:03 UTC, Elabajaba commented
I haven't ran it locally, but the test output tends to change a bit on wgpu/naga upgrades.

2024-07-25 09:03 UTC, teoxoy commented
I put up https://github.com/gfx-rs/wgpu/pull/6045 that will be backported and part of the 22.1 release.

2024-08-01 04:13 UTC, JMS55 commented
Naga 22.1 has released with PartialEq back on types.

2024-08-01 16:58 UTC, callym commented
I've updated some failing tests - to me it looks like just the numbering in the error message is different

2024-08-01 17:23 UTC, JMS55 requested changes

2024-08-01 17:23 UTC, JMS55 commented on Cargo.toml
> +naga = { version = "22", features = ["wgsl-in", "wgsl-out"] }
We should depend on 22.1 explicitly.

2024-08-01 21:11 UTC, callym commented
The test failures are assertions that were never hit before because they used `#[cfg(debug)]` instead of `#[cfg(debug_assertions)]`

2024-08-02 20:19 UTC, JMS55 approved these changes

2024-08-03 02:19 UTC, superdump commented on Cargo.toml
> +wgpu = { version = "22", features = ["naga-ir"] }
Also 22.1?

2024-08-03 02:22 UTC, superdump approved these changes

2024-08-03 06:37 UTC, mockersf approved these changes

2024-08-03 06:38 UTC, merged